# Generated by Django 5.2.12 on 2026-04-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'марка',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.category')),
            ],
            options={
                'db_table': 'категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id_продукт', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='название', max_length=200)),
                ('price', models.DecimalField(db_column='цена', decimal_places=2, max_digits=10)),
                ('unit', models.CharField(db_column='ед_измерения', max_length=20)),
                ('status', models.CharField(db_column='состояние', max_length=50)),
                ('brand', models.ForeignKey(db_column='id_марка', on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
                ('category', models.ForeignKey(db_column='id_категория', on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'продукт',
            },
        ),
    ]
